AllCops:
  TargetRubyVersion: 2.3
  # Display warning with reference URL
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md
  Exclude:
    - "vendor/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

inherit_from: .rubocop_todo.yml
