AllCops:
  TargetRubyVersion: 2.3
  # Display warning with reference URL
  DisplayStyleGuide: true
  StyleGuideBaseURL: https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md
  Exclude:
    - "vendor/**/*"

# Checks the indentation of here document closings.
Layout/ClosingHeredocIndentation:
  Enabled: true

# Use only ascii symbols in comments.
AsciiComments:
  Enabled: false

# Unnecessary blank line at the beginning of the source.
Layout/LeadingBlankLines:
  Enabled: true

# Use 'set_' and 'get_' prefix
AccessorMethodName:
  Enabled: false

# Surrounding space missing in default value assignment.
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

# private does not make singleton methods private. Use private_class_method or private inside a class << self block instead.
Lint/IneffectiveAccessModifier:
  Enabled: false

# Useless private access modifier.
Lint/UselessAccessModifier:
  Enabled: false

# Offense count: 12
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 108
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

# Method has too many lines.
Metrics/MethodLength:
  Enabled: false

# Use meaningful heredoc delimiters.
Naming/HeredocDelimiterNaming:
  Enabled: false

# Do not place comments on the same line as the class keyword.
Style/CommentedKeyword:
  Enabled: false

# Web API respons includes "<Datetime>" elements.
Style/DateTime:
  Enabled: false

# Missing top-level class documentation comment.
Style/Documentation:
  Enabled: false

# Missing magic comment # frozen_string_literal: true.
Style/FrozenStringLiteralComment:
  Enabled: false

# Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
# https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.md#if-as-a-modifier
Style/IfUnlessModifier:
  Enabled: false

# Freeze mutable objects assigned to constants.
Style/MutableConstant:
  Enabled: false

# Use underscores(_) as decimal mark and separate every 3 digits with them.
Style/NumericLiterals:
  MinDigits: 8

# Use element.attributes.size.positive? instead of element.attributes.size > 0.
# https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.md#predicate-methods
Style/NumericPredicate:
  Enabled: false

# Redundant self detected.
# https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.md#no-self-unless-required
Style/RedundantSelf:
  Enabled: false

# Use %r around regular expression.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Enabled: false

# Use !empty? instead of size > 0.
Style/ZeroLengthPredicate:
  Enabled: false
